resume_headers = [
    # general
    "profile", "objective", "summary", "highlights", "qualifications", "accomplishments",
    "achievements", "contact information",

    # experience
    "experience", "work experience", "professional experience", "relevant experience",
    "employment history", "career history", "positions held", "work history",

    # education
    "education", "academic background", "academic history", "academic qualifications",
    "educational background", "educational qualifications", "certifications", "licenses",
    "training", "professional development", "continuing education",

    # skills
    "skills", "technical skills", "core skills", "key skills", "professional skills",
    "competencies", "tools", "technologies", "programming languages",
    "languages", "skills and interests", "technical proficiency",

    # projects / research
    "projects", "key projects", "research", "research experience", "publications",
    "presentations", "conferences", "patents", "project experience",

    # leadership / awards / misc
    "volunteer experience", "community service", "leadership", "awards", "honors",
    "affiliations", "memberships", "professional memberships", "interests", "hobbies",
    "references"
]

experience_headers = [
    "experience", "work experience", "professional experience", "relevant experience",
    "employment history", "career history", "positions held", "work history"
]

education_headers = [
    "education", "academic background", "academic history", "academic qualifications",
    "educational background", "educational qualifications", "certifications", "licenses",
    "training", "professional development", "continuing education"
]

projects_headers = [
    "projects", "key projects", "research", "research experience", "publications",
    "presentations", "conferences", "patents", "project experience"
]

skills_headers = [
    "skills", "technical skills", "core skills", "key skills", "professional skills",
    "competencies", "tools", "technologies", "programming languages",
    "languages", "skills and interests", "technical proficiency", "relevant skills"
]



misc_headers = [
    # leadership / awards / misc
    "volunteer experience", "community service", "leadership", "awards", "honors",
    "affiliations", "memberships", "professional memberships", "interests", "hobbies",
    "references"
]

job_titles_keywords = [
    "engineer", "engineering", "scientist", "scientists", "technician", "technicians",
    "technologist", "technologists", "developer", "developers", "programmer", "programmers",
    "analyst", "analysts", "designer", "designers", "architect", "architects", "researcher", "researchers",
    "manager", "managers", "director", "directors", "supervisor", "supervisors", "fellow", "fellows",
    "senior", "seniority", "junior", "juniority", "principal", "principals", "lead", "leads",
    "head", "heads", "chief", "chiefs", "executive", "executives", "consultant", "consultants",
    "advisor", "advisors", "advisor", "advisors", "advisor", "advisors", "advisor", "advisors", "intern", "internship"

]

common_words = {
        # Articles
        'a', 'an', 'the',
        
        # Conjunctions
        'and', 'or', 'but', 'nor', 'for', 'yet', 'so', 'as', 'if',
        
        # Prepositions
        'in', 'on', 'at', 'to', 'from', 'with', 'by', 'about', 'against',
        'between', 'into', 'through', 'during', 'before', 'after', 'above',
        'below', 'up', 'down', 'out', 'off', 'over', 'under', 'again',
        'further', 'then', 'once', 'of', 'throughout', 'within', 'without',
        
        # Pronouns
        'i', 'you', 'he', 'she', 'it', 'we', 'they', 'them', 'their',
        'this', 'that', 'these', 'those', 'my', 'your', 'his', 'her',
        'its', 'our', 'who', 'which', 'what', 'whose', 'anyone', 'someone',
        
        # Be verbs and helpers
        'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has',
        'had', 'do', 'does', 'did', 'will', 'would', 'should', 'could',
        'may', 'might', 'must', 'can', 'shall', 'ought',
        
        # Common verbs (too generic for ATS)
        'get', 'got', 'make', 'made', 'go', 'went', 'take', 'took', 'come',
        'came', 'see', 'saw', 'know', 'knew', 'think', 'thought', 'give',
        'gave', 'find', 'found', 'tell', 'told', 'become', 'became',
        'leave', 'left', 'feel', 'felt', 'bring', 'brought', 'begin',
        'began', 'keep', 'kept', 'let', 'put', 'seem', 'seemed',
        'run', 'ran', 'set', 'sit', 'sat', 'stand', 'stood', 'said',
        
        # Common business fluff words
        'etc', 'eg', 'ie', 'vs', 'via', 'per', 'all', 'any', 'each',
        'every', 'some', 'few', 'more', 'most', 'other', 'such', 'only',
        'own', 'same', 'than', 'too', 'very', 'just', 'also', 'well',
        'even', 'back', 'there', 'here', 'where', 'when', 'how', 'why',
        'because', 'since', 'while', 'although', 'though', 'both',
        'either', 'neither', 'whether', 'not', 'no', 'yes',
        
        # Common job posting words (not skills)
        'will', 'work', 'working', 'ability', 'able', 'including',
        'include', 'includes', 'various', 'multiple', 'related',
        'required', 'preferred', 'minimum', 'plus', 'must', 'needs',
        'need', 'help', 'helping', 'looking', 'seeking', 'wanted'
    }

keywords = [
    # Responsibilities / Duties
    "responsibilities", "key responsibilities", "primary responsibilities", "main responsibilities",
    "job responsibilities", "responsibility", "responsible for", "duties", "job duties",
    "essential duties", "tasks", "key tasks", "what you'll do", "day-to-day",
    "what you will be doing",

    # Requirements / Qualifications
    "requirements", "job requirements", "position requirements", "required", "must have",
    "must possess", "you must", "mandatory", "minimum requirements", "qualifications",
    "required qualifications", "desired qualifications", "preferred qualifications",
    "basic qualifications", "minimum qualifications", "skills and qualifications",
    "experience", "work experience", "background", "knowledge", "abilities", "competencies",

    # Preferred / Nice-to-Have
    "preferred", "preferred skills", "preferred qualifications", "desired", "desired skills",
    "nice to have", "asset", "bonus points for", "strongly preferred",

    # Skills
    "skills", "key skills", "technical skills", "soft skills", "core skills",
    "required skills", "skill set",

    # Benefits / Perks
    "benefits", "compensation and benefits", "salary and benefits", "what we offer",
    "we offer", "perks", "employee benefits", "our benefits", "compensation",
    "salary", "remuneration", "what you get",

    # Company / Culture
    "about us", "about the company", "about", "company overview", "who we are",
    "our mission", "our values", "company profile", "culture", "working with us",

    # Application / How to Apply
    "how to apply", "application process", "apply now", "to apply", "your application",
    "submit your resume", "application instructions", "application deadline",

    # Other Catch-alls
    "position summary", "role summary", "job summary", "the role", "position overview",
    "job overview", "what we’re looking for", "ideal candidate", "candidate profile",
    "who you are"
]

eng_keywords = [
    "process design",
    "process engineering",
    "chemical engineering",
    "process design",
    "process engineering",
    "chemical engineering",
    "mass transfer",
    "heat transfer",
    "reaction engineering",
    "unit operations",
    "thermodynamics",
    "kinetics",
    "fluid dynamics",
    "process control",
    "control systems",
    "pid tuning",
    "instrumentation",
    "piping",
    "pfd",
    "p&id",
    "material balance",
    "energy balance",
    "hysys",
    "aspen hysys",
    "aspen plus",
    "aspentech",
    "comsol",
    "ansys fluent",
    "cfd",
    "process simulation",
    "process optimization",
    "distillation",
    "extraction",
    "absorption",
    "adsorption",
    "membrane separation",
    "chromatography",
    "crystallization",
    "polymers",
    "polymerization",
    "catalysis",
    "catalytic reactors",
    "bioreactors",
    "fermentation",
    "downstream processing",
    "scale-up",
    "pilot plant",
    "hazop",
    "psm",
    "process safety management",
    "osha",
    "six sigma",
    "lean",
    "doe",
    "design of experiments",
    "gmp",
    "good manufacturing practice",
    "validation",
    "quality control",
    "process improvement",
    "process development",
    "process troubleshooting",
    "reaction kinetics",
    "corrosion",
    "heat exchanger",
    "reactor design",
    "distillation column",
    "tray column",
    "packed bed",
    "fluidized bed",
    "absorber",
    "stripper",
    "evaporation",
    "filtration",
    "centrifugation",
    "mixing",
    "agitation",
    "rheology",
    "viscosity",
    "phase equilibrium",
    "vapor liquid equilibrium",
    "equation of state",
    "fugacity",
    "activity coefficient",
    "adsorption isotherms",
    "langmuir",
    "freundlich",
    "cstr",
    "pfr",
    "batch reactor",
    "continuous reactor",
    "biofuels",
    "petrochemicals",
    "refining",
    "polyethylene",
    "polypropylene",
    "pharmaceutical engineering",
    "biochemical engineering",
    "nanomaterials",
    "materials science",
    "corrosion engineering",
    "electrochemistry",
    "batteries",
    "fuel cells",
    "membranes",
    "water treatment",
    "wastewater treatment",
    "air pollution control",
    "environmental engineering",
    "hazardous waste",
    "green engineering",
    "renewable energy",
    "solar cells",
    "hydrogen production",
    "carbon capture",
    "sequestration",
    "life cycle assessment",
    "sustainability",
    "heat exchanger network",
    "pinch analysis",
    "process intensification",
    "modular process",
    "sorbents",
    "desiccant",
    "scrubber",
    "flares",
    "flare system",
    "safety relief valves",
    "instrumentation and control",
    "scada",
    "plc",
    "distributed control system",
    "batch records",
    "standard operating procedure",
    "process flow",
    "asme",
    "api",
    "iso 9001",
    "nfpa",
    "nfpa 30",
    "nfpa 70",
    "osha 1910",
    "fermentation scale-up",
    "clean-in-place",
    "sterilization",
    "biosafety",
    "toxicology",
    "occupational safety",
    "absorption tower",
    "activated carbon",
    "adsorption",
    "agitator design",
    "air separation",
    "alumina catalyst",
    "anhydrous ammonia",
    "anisotropic etching",
    "aqueous solution",
    "arc flash analysis",
    "aspen hysys",
    "aspen plus",
    "batch distillation",
    "benzene removal",
    "bioethanol",
    "bioreactor",
    "biosorption",
    "boiling point elevation",
    "boundary layer diffusion",
    "btex removal",
    "bubble column",
    "butadiene production",
    "catalytic cracking",
    "catalyst regeneration",
    "chromatography",
    "clean in place",
    "claus process",
    "comsol multiphysics",
    "compressible flow",
    "conduction heat transfer",
    "continuous stirred tank reactor",
    "control valve sizing",
    "corrosion inhibition",
    "coulter counter",
    "crystallization",
    "cyclone separator",
    "deaeration",
    "debottlenecking",
    "dehydration unit",
    "demister pad",
    "density functional theory",
    "desalination",
    "desiccant dryer",
    "detonation modeling",
    "diesel hydrotreating",
    "differential distillation",
    "diffusion coefficient",
    "distillation column",
    "distributed control system",
    "drying kinetics",
    "dynamic simulation",
    "electrochemical cell",
    "electrocoagulation",
    "emulsion polymerization",
    "enthalpy balance",
    "enzyme immobilization",
    "ethylene oxide",
    "evaporation",
    "extractive distillation",
    "fermentation kinetics",
    "fischer tropsch synthesis",
    "flash distillation",
    "fluidized bed",
    "flue gas desulfurization",
    "fouling resistance",
    "fractional distillation",
    "fuel cells",
    "gas absorption",
    "gas chromatography",
    "gas lift reactor",
    "gas sweetening",
    "geometric similarity",
    "gibbs free energy",
    "glycol dehydration",
    "hazop study",
    "heat exchanger network",
    "heterogeneous catalysis",
    "homogeneous catalysis",
    "hydraulic diameter",
    "hydrodynamic stability",
    "hydrogen sulfide removal",
    "hydrotreating",
    "immiscible liquids",
    "industrial catalysis",
    "inertial impaction",
    "ion exchange",
    "isomerization",
    "joule thomson effect",
    "kinetic modeling",
    "laminar flow reactor",
    "langmuir adsorption isotherm",
    "le chatelier principle",
    "lean amine solution",
    "liquid liquid extraction",
    "mass balance",
    "mass diffusivity",
    "mass transfer coefficient",
    "membrane filtration",
    "micellar catalysis",
    "mixed flow reactor",
    "mixing time",
    "multiphase flow",
    "nanofiltration",
    "natural gas processing",
    "nucleation",
    "packed column",
    "particle size distribution",
    "pfd",
    "piping and instrumentation diagram",
    "plant commissioning",
    "plug flow reactor",
    "porous catalyst",
    "pre combustion capture",
    "pressure drop calculation",
    "pressure swing adsorption",
    "process control",
    "process hazard analysis",
    "process intensification",
    "process safety management",
    "process simulation",
    "psa unit",
    "pyrolysis",
    "raoult law",
    "rate based model",
    "reaction kinetics",
    "reaction rate constant",
    "reactor design",
    "reboiler",
    "rectification",
    "reflux ratio",
    "refrigeration cycle",
    "residence time distribution",
    "reverse osmosis",
    "rheology",
    "saponification",
    "scrubber design",
    "separation process",
    "six sigma dmaic",
    "slurry reactor",
    "solubility parameter",
    "solid liquid extraction",
    "solvent recovery",
    "sorption isotherm",
    "spray drying",
    "steam reforming",
    "steam stripping",
    "stefan boltzmann law",
    "stirred tank reactor",
    "stoichiometric balance",
    "sulfur recovery",
    "supercritical fluid extraction",
    "thermodynamic equilibrium",
    "tray efficiency",
    "troubleshooting process",
    "turbulent flow",
    "unit operation",
    "vacuum distillation",
    "vapor liquid equilibrium",
    "venturi scrubber",
    "viscosity index",
    "waste heat recovery",
    "wastewater treatment",
    "zeolite catalysis",

    "electrical engineering",
    "circuit design",
    "pcb",
    "pcb layout",
    "schematic capture",
    "altium",
    "cadence",
    "orCAD",
    "eagle",
    "proteus",
    "multisim",
    "spice",
    "ltspice",
    "pSpice",
    "analog design",
    "digital design",
    "mixed-signal",
    "signal processing",
    "image processing",
    "dsp",
    "fourier transform",
    "filter design",
    "adc",
    "dac",
    "data converters",
    "low noise amplifier",
    "rf",
    "microwave",
    "antenna design",
    "electromagnetics",
    "transmission line",
    "waveguide",
    "power electronics",
    "inverter",
    "converter",
    "buck converter",
    "boost converter",
    "flyback",
    "bridge rectifier",
    "motor control",
    "servo",
    "stepper",
    "ac motors",
    "dc motors",
    "brushless",
    "embedded systems",
    "microcontroller",
    "arm",
    "stm32",
    "arduino",
    "raspberry pi",
    "fpga",
    "asic",
    "soc",
    "verilog",
    "vhdl",
    "rtl design",
    "systemverilog",
    "logic synthesis",
    "timing analysis",
    "eda tools",
    "synopsys",
    "mentor graphics",
    "xilinx",
    "intel quartus",
    "altera",
    "simulation",
    "matlab",
    "simulink",
    "python",
    "c",
    "c++",
    "embedded c",
    "firmware",
    "device drivers",
    "rtos",
    "freeRTOS",
    "baremetal",
    "wireless",
    "wifi",
    "bluetooth",
    "zigbee",
    "nfc",
    "rfid",
    "iot",
    "lpwan",
    "lorawan",
    "cellular",
    "lte",
    "5g",
    "modulation",
    "qam",
    "psk",
    "fsk",
    "ofdm",
    "channel coding",
    "error correction",
    "crc",
    "reed solomon",
    "turbo codes",
    "ldpc",
    "control systems",
    "feedback",
    "pid controller",
    "state space",
    "kalman filter",
    "observer design",
    "bode plot",
    "nyquist",
    "stability analysis",
    "resonance",
    "impedance",
    "admittance",
    "crosstalk",
    "emc",
    "emi",
    "grounding",
    "shielding",
    "esd",
    "power supplies",
    "ups",
    "batteries",
    "solar inverter",
    "renewable energy",
    "hvac",
    "hvdc",
    "transformer",
    "substation",
    "grid integration",
    "scada",
    "protection",
    "relay",
    "breaker",
    "switchgear",
    "smart grid",
    "phd sensor",
    "oscilloscope",
    "logic analyzer",
    "spectrum analyzer",
    "network analyzer",
    "multimeter",
    "function generator",
    "mechanical engineering",
    "solidworks",
    "autocad",
    "catia",
    "creo",
    "nx",
    "proe",
    "fusion360",
    "cad",
    "cam",
    "fea",
    "finite element analysis",
    "stress analysis",
    "strain",
    "fatigue",
    "fracture mechanics",
    "thermal analysis",
    "ansys",
    "abaqus",
    "comsol",
    "nastran",
    "patran",
    "hypermesh",
    "cfd",
    "computational fluid dynamics",
    "fluent",
    "star-ccm+",
    "openfoam",
    "heat transfer",
    "conduction",
    "convection",
    "radiation",
    "thermodynamics",
    "fluid mechanics",
    "turbomachinery",
    "pumps",
    "compressors",
    "fans",
    "valves",
    "bearings",
    "gearbox",
    "shafts",
    "cams",
    "linkages",
    "dynamics",
    "kinematics",
    "vibration",
    "modal analysis",
    "rotordynamics",
    "tribology",
    "lubrication",
    "manufacturing",
    "machining",
    "cnc",
    "lathe",
    "milling",
    "drilling",
    "grinding",
    "edm",
    "casting",
    "forging",
    "welding",
    "brazing",
    "additive manufacturing",
    "3d printing",
    "sls",
    "sla",
    "fdm",
    "injection molding",
    "extrusion",
    "sheet metal",
    "gd&t",
    "tolerance analysis",
    "iso 2768",
    "asme y14.5",
    "quality control",
    "six sigma",
    "lean manufacturing",
    "kaizen",
    "tpm",
    "dfm",
    "dfa",
    "dfmea",
    "pfmea",
    "reliability",
    "maintenance",
    "hvac",
    "refrigeration",
    "heat exchangers",
    "boilers",
    "engines",
    "internal combustion",
    "diesel engine",
    "gas turbine",
    "jet engine",
    "rocket propulsion",
    "aerospace",
    "automotive",
    "nvh",
    "suspension",
    "brakes",
    "steering",
    "chassis",
    "mechatronics",
    "robotics",
    "servo motor",
    "actuator",
    "sensors",
    "controls",
    "pid",
    "plc",
    "automation",
    "mechatronic systems",
    "materials science",
    "metallurgy",
    "composites",
    "polymers",
    "ceramics",
    "alloys",
    "fracture toughness",
    "hardness",
    "fatigue life",
    "creep",
    "corrosion",
    "coatings",
    "tribological properties",

    "computer science",
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "go",
    "rust",
    "ruby",
    "php",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "node",
    "express",
    "django",
    "flask",
    "fastapi",
    "spring",
    "hibernate",
    "sql",
    "postgres",
    "mysql",
    "sqlite",
    "oracle",
    "mssql",
    "nosql",
    "mongodb",
    "redis",
    "cassandra",
    "neo4j",
    "elasticsearch",
    "graphql",
    "rest api",
    "grpc",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "ci",
    "cd",
    "testing",
    "unit testing",
    "pytest",
    "junit",
    "selenium",
    "cypress",
    "playwright",
    "puppeteer",
    "aws",
    "azure",
    "gcp",
    "cloud computing",
    "serverless",
    "microservices",
    "monolith",
    "design patterns",
    "oop",
    "functional programming",
    "absorption",
    "absorption analysis",
    "absorption design",
    "absorption modeling",
    "absorption optimization",
    "absorption simulation",
    "absorption testing",
    "adsorption",
    "adsorption analysis",
    "adsorption design",
    "adsorption modeling",
    "adsorption optimization",
    "adsorption simulation",
    "adsorption testing",
    "aspen",
    "aspen analysis",
    "aspen design",
    "aspen modeling",
    "aspen optimization",
    "aspen simulation",
    "aspen testing",
    "bioethanol",
    "bioethanol analysis",
    "bioethanol design",
    "bioethanol modeling",
    "bioethanol optimization",
    "bioethanol simulation",
    "bioethanol testing",
    "catalysis",
    "catalysis analysis",
    "catalysis design",
    "catalysis modeling",
    "catalysis optimization",
    "catalysis simulation",
    "catalysis testing",
    "compressor",
    "compressor analysis",
    "compressor design",
    "compressor modeling",
    "compressor optimization",
    "compressor simulation",
    "compressor testing",
    "crystallization",
    "crystallization analysis",
    "crystallization design",
    "crystallization modeling",
    "crystallization optimization",
    "crystallization simulation",
    "crystallization testing",
    "cstr",
    "cstr analysis",
    "cstr design",
    "cstr modeling",
    "cstr optimization",
    "cstr simulation",
    "cstr testing",
    "distillation",
    "distillation analysis",
    "distillation design",
    "distillation modeling",
    "distillation optimization",
    "distillation simulation",
    "distillation testing",
    "fermentation",
    "fermentation analysis",
    "fermentation design",
    "fermentation modeling",
    "fermentation optimization",
    "fermentation simulation",
    "fermentation testing",
    "fluidization",
    "fluidization analysis",
    "fluidization design",
    "fluidization modeling",
    "fluidization optimization",
    "fluidization simulation",
    "fluidization testing",
    "hazop",
    "hazop analysis",
    "hazop design",
    "hazop modeling",
    "hazop optimization",
    "hazop simulation",
    "hazop testing",
    "heat exchanger",
    "heat exchanger analysis",
    "heat exchanger design",
    "heat exchanger modeling",
    "heat exchanger optimization",
    "heat exchanger simulation",
    "heat exchanger testing",
    "hysys",
    "hysys analysis",
    "hysys design",
    "hysys modeling",
    "hysys optimization",
    "hysys simulation",
    "hysys testing",
    "mass transfer",
    "mass transfer analysis",
    "mass transfer design",
    "mass transfer modeling",
    "mass transfer optimization",
    "mass transfer simulation",
    "mass transfer testing",
    "membrane",
    "membrane analysis",
    "membrane design",
    "membrane modeling",
    "membrane optimization",
    "membrane simulation",
    "membrane testing",
    "p&id",
    "p&id analysis",
    "p&id design",
    "p&id modeling",
    "p&id optimization",
    "p&id simulation",
    "p&id testing",
    "pfd",
    "pfd analysis",
    "pfd design",
    "pfd modeling",
    "pfd optimization",
    "pfd simulation",
    "pfd testing",
    "pfr",
    "pfr analysis",
    "pfr design",
    "pfr modeling",
    "pfr optimization",
    "pfr simulation",
    "pfr testing",
    "polymerization",
    "polymerization analysis",
    "polymerization design",
    "polymerization modeling",
    "polymerization optimization",
    "polymerization simulation",
    "polymerization testing",
    "process control",
    "process control analysis",
    "process control design",
    "process control modeling",
    "process control optimization",
    "process control simulation",
    "process control testing",
    "psm",
    "psm analysis",
    "psm design",
    "psm modeling",
    "psm optimization",
    "psm simulation",
    "psm testing",
    "pumps",
    "pumps analysis",
    "pumps design",
    "pumps modeling",
    "pumps optimization",
    "pumps simulation",
    "pumps testing",
    "pyrolysis",
    "pyrolysis analysis",
    "pyrolysis design",
    "pyrolysis modeling",
    "pyrolysis optimization",
    "pyrolysis simulation",
    "pyrolysis testing",
    "reaction kinetics",
    "reaction kinetics analysis",
    "reaction kinetics design",
    "reaction kinetics modeling",
    "reaction kinetics optimization",
    "reaction kinetics simulation",
    "reaction kinetics testing",
    "separation",
    "separation analysis",
    "separation design",
    "separation modeling",
    "separation optimization",
    "separation simulation",
    "separation testing",
    "thermodynamics",
    "thermodynamics analysis",
    "thermodynamics design",
    "thermodynamics modeling",
    "thermodynamics optimization",
    "thermodynamics simulation",
    "thermodynamics testing",
    "turbine",
    "turbine analysis",
    "turbine design",
    "turbine modeling",
    "turbine optimization",
    "turbine simulation",
    "turbine testing",
    "wastewater",
    "wastewater analysis",
    "wastewater design",
    "wastewater modeling",
    "wastewater optimization",
    "wastewater simulation",
    "wastewater testing",
    "actuator",
    "actuator analysis",
    "actuator design",
    "actuator modeling",
    "actuator optimization",
    "actuator simulation",
    "actuator testing",
    "adc",
    "adc analysis",
    "adc design",
    "adc modeling",
    "adc optimization",
    "adc simulation",
    "adc testing",
    "analog",
    "analog analysis",
    "analog design",
    "analog modeling",
    "analog optimization",
    "analog simulation",
    "analog testing",
    "antenna",
    "antenna analysis",
    "antenna design",
    "antenna modeling",
    "antenna optimization",
    "antenna simulation",
    "antenna testing",
    "arduino",
    "arduino analysis",
    "arduino design",
    "arduino modeling",
    "arduino optimization",
    "arduino simulation",
    "arduino testing",
    "asic",
    "asic analysis",
    "asic design",
    "asic modeling",
    "asic optimization",
    "asic simulation",
    "asic testing",
    "circuit",
    "circuit analysis",
    "circuit design",
    "circuit modeling",
    "circuit optimization",
    "circuit simulation",
    "circuit testing",
    "cmos",
    "cmos analysis",
    "cmos design",
    "cmos modeling",
    "cmos optimization",
    "cmos simulation",
    "cmos testing",
    "dac",
    "dac analysis",
    "dac design",
    "dac modeling",
    "dac optimization",
    "dac simulation",
    "dac testing",
    "digital",
    "digital analysis",
    "digital design",
    "digital modeling",
    "digital optimization",
    "digital simulation",
    "digital testing",
    "dsp",
    "dsp analysis",
    "dsp design",
    "dsp modeling",
    "dsp optimization",
    "dsp simulation",
    "dsp testing",
    "electromagnetics",
    "electromagnetics analysis",
    "electromagnetics design",
    "electromagnetics modeling",
    "electromagnetics optimization",
    "electromagnetics simulation",
    "electromagnetics testing",
    "embedded",
    "embedded analysis",
    "embedded design",
    "embedded modeling",
    "embedded optimization",
    "embedded simulation",
    "embedded testing",
    "fpga",
    "fpga analysis",
    "fpga design",
    "fpga modeling",
    "fpga optimization",
    "fpga simulation",
    "fpga testing",
    "microcontroller",
    "microcontroller analysis",
    "microcontroller design",
    "microcontroller modeling",
    "microcontroller optimization",
    "microcontroller simulation",
    "microcontroller testing",
    "pcb",
    "pcb analysis",
    "pcb design",
    "pcb modeling",
    "pcb optimization",
    "pcb simulation",
    "pcb testing",
    "power electronics",
    "power electronics analysis",
    "power electronics design",
    "power electronics modeling",
    "power electronics optimization",
    "power electronics simulation",
    "power electronics testing",
    "raspberry pi",
    "raspberry pi analysis",
    "raspberry pi design",
    "raspberry pi modeling",
    "raspberry pi optimization",
    "raspberry pi simulation",
    "raspberry pi testing",
    "rf",
    "rf analysis",
    "rf design",
    "rf modeling",
    "rf optimization",
    "rf simulation",
    "rf testing",
    "rtl",
    "rtl analysis",
    "rtl design",
    "rtl modeling",
    "rtl optimization",
    "rtl simulation",
    "rtl testing",
    "semiconductor",
    "semiconductor analysis",
    "semiconductor design",
    "semiconductor modeling",
    "semiconductor optimization",
    "semiconductor simulation",
    "semiconductor testing",
    "sensor",
    "sensor analysis",
    "sensor design",
    "sensor modeling",
    "sensor optimization",
    "sensor simulation",
    "sensor testing",
    "signals",
    "signals analysis",
    "signals design",
    "signals modeling",
    "signals optimization",
    "signals simulation",
    "signals testing",
    "spice",
    "spice analysis",
    "spice design",
    "spice modeling",
    "spice optimization",
    "spice simulation",
    "spice testing",
    "transistor",
    "transistor analysis",
    "transistor design",
    "transistor modeling",
    "transistor optimization",
    "transistor simulation",
    "transistor testing",
    "verilog",
    "verilog analysis",
    "verilog design",
    "verilog modeling",
    "verilog optimization",
    "verilog simulation",
    "verilog testing",
    "vhdl",
    "vhdl analysis",
    "vhdl design",
    "vhdl modeling",
    "vhdl optimization",
    "vhdl simulation",
    "vhdl testing",
    "wireless",
    "wireless analysis",
    "wireless design",
    "wireless modeling",
    "wireless optimization",
    "wireless simulation",
    "wireless testing",

    "ansys",
    "ansys analysis",
    "ansys design",
    "ansys modeling",
    "ansys optimization",
    "ansys simulation",
    "ansys testing",
    "autocad",
    "autocad analysis",
    "autocad design",
    "autocad modeling",
    "autocad optimization",
    "autocad simulation",
    "autocad testing",
    "bearings",
    "bearings analysis",
    "bearings design",
    "bearings modeling",
    "bearings optimization",
    "bearings simulation",
    "bearings testing",
    "cad",
    "cad analysis",
    "cad design",
    "cad modeling",
    "cad optimization",
    "cad simulation",
    "cad testing",
    "cam",
    "cam analysis",
    "cam design",
    "cam modeling",
    "cam optimization",
    "cam simulation",
    "cam testing",
    "casting",
    "casting analysis",
    "casting design",
    "casting modeling",
    "casting optimization",
    "casting simulation",
    "casting testing",
    "cnc",
    "cnc analysis",
    "cnc design",
    "cnc modeling",
    "cnc optimization",
    "cnc simulation",
    "cnc testing",
    "combustion",
    "combustion analysis",
    "combustion design",
    "combustion modeling",
    "combustion optimization",
    "combustion simulation",
    "combustion testing",
    "dynamics",
    "dynamics analysis",
    "dynamics design",
    "dynamics modeling",
    "dynamics optimization",
    "dynamics simulation",
    "dynamics testing",
    "fatigue",
    "fatigue analysis",
    "fatigue design",
    "fatigue modeling",
    "fatigue optimization",
    "fatigue simulation",
    "fatigue testing",
    "fea",
    "fea analysis",
    "fea design",
    "fea modeling",
    "fea optimization",
    "fea simulation",
    "fea testing",
    "fluid mechanics",
    "fluid mechanics analysis",
    "fluid mechanics design",
    "fluid mechanics modeling",
    "fluid mechanics optimization",
    "fluid mechanics simulation",
    "fluid mechanics testing",
    "gd&t",
    "gd&t analysis",
    "gd&t design",
    "gd&t modeling",
    "gd&t optimization",
    "gd&t simulation",
    "gd&t testing",
    "gearbox",
    "gearbox analysis",
    "gearbox design",
    "gearbox modeling",
    "gearbox optimization",
    "gearbox simulation",
    "gearbox testing",
    "heat transfer",
    "heat transfer analysis",
    "heat transfer design",
    "heat transfer modeling",
    "heat transfer optimization",
    "heat transfer simulation",
    "heat transfer testing",
    "hvac",
    "hvac analysis",
    "hvac design",
    "hvac modeling",
    "hvac optimization",
    "hvac simulation",
    "hvac testing",
    "kinematics",
    "kinematics analysis",
    "kinematics design",
    "kinematics modeling",
    "kinematics optimization",
    "kinematics simulation",
    "kinematics testing",
    "manufacturing",
    "manufacturing analysis",
    "manufacturing design",
    "manufacturing modeling",
    "manufacturing optimization",
    "manufacturing simulation",
    "manufacturing testing",
    "materials",
    "materials analysis",
    "materials design",
    "materials modeling",
    "materials optimization",
    "materials simulation",
    "materials testing",
    "mechanics",
    "mechanics analysis",
    "mechanics design",
    "mechanics modeling",
    "mechanics optimization",
    "mechanics simulation",
    "mechanics testing",
    "pumps",
    "pumps analysis",
    "pumps design",
    "pumps modeling",
    "pumps optimization",
    "pumps simulation",
    "pumps testing",
    "solidworks",
    "solidworks analysis",
    "solidworks design",
    "solidworks modeling",
    "solidworks optimization",
    "solidworks simulation",
    "solidworks testing",
    "thermodynamics",
    "thermodynamics analysis",
    "thermodynamics design",
    "thermodynamics modeling",
    "thermodynamics optimization",
    "thermodynamics simulation",
    "thermodynamics testing",
    "tribology",
    "tribology analysis",
    "tribology design",
    "tribology modeling",
    "tribology optimization",
    "tribology simulation",
    "tribology testing",
    "turbomachinery",
    "turbomachinery analysis",
    "turbomachinery design",
    "turbomachinery modeling",
    "turbomachinery optimization",
    "turbomachinery simulation",
    "turbomachinery testing",
    "welding",
    "welding analysis",
    "welding design",
    "welding modeling",
    "welding optimization",
    "welding simulation",
    "welding testing",

    "ai",
    "ai analysis",
    "ai design",
    "ai modeling",
    "ai optimization",
    "ai simulation",
    "ai testing",
    "api",
    "api analysis",
    "api design",
    "api modeling",
    "api optimization",
    "api simulation",
    "api testing",
    "aws",
    "aws analysis",
    "aws design",
    "aws modeling",
    "aws optimization",
    "aws simulation",
    "aws testing",
    "azure",
    "azure analysis",
    "azure design",
    "azure modeling",
    "azure optimization",
    "azure simulation",
    "azure testing",
    "c",
    "c analysis",
    "c design",
    "c modeling",
    "c optimization",
    "c simulation",
    "c testing",
    "c++",
    "c++ analysis",
    "c++ design",
    "c++ modeling",
    "c++ optimization",
    "c++ simulation",
    "c++ testing",
    "css",
    "css analysis",
    "css design",
    "css modeling",
    "css optimization",
    "css simulation",
    "css testing",
    "deep learning",
    "deep learning analysis",
    "deep learning design",
    "deep learning modeling",
    "deep learning optimization",
    "deep learning simulation",
    "deep learning testing",
    "distributed systems",
    "distributed systems analysis",
    "distributed systems design",
    "distributed systems modeling",
    "distributed systems optimization",
    "distributed systems simulation",
    "distributed systems testing",
    "docker",
    "docker analysis",
    "docker design",
    "docker modeling",
    "docker optimization",
    "docker simulation",
    "docker testing",
    "gcp",
    "gcp analysis",
    "gcp design",
    "gcp modeling",
    "gcp optimization",
    "gcp simulation",
    "gcp testing",
    "git",
    "git analysis",
    "git design",
    "git modeling",
    "git optimization",
    "git simulation",
    "git testing",
    "github",
    "github analysis",
    "github design",
    "github modeling",
    "github optimization",
    "github simulation",
    "github testing",
    "go",
    "go analysis",
    "go design",
    "go modeling",
    "go optimization",
    "go simulation",
    "go testing",
    "graphql",
    "graphql analysis",
    "graphql design",
    "graphql modeling",
    "graphql optimization",
    "graphql simulation",
    "graphql testing",
    "hadoop",
    "hadoop analysis",
    "hadoop design",
    "hadoop modeling",
    "hadoop optimization",
    "hadoop simulation",
    "hadoop testing",
    "html",
    "html analysis",
    "html design",
    "html modeling",
    "html optimization",
    "html simulation",
    "html testing",
    "java",
    "java analysis",
    "java design",
    "java modeling",
    "java optimization",
    "java simulation",
    "java testing",
    "javascript",
    "javascript analysis",
    "javascript design",
    "javascript modeling",
    "javascript optimization",
    "javascript simulation",
    "javascript testing",
    "kubernetes",
    "kubernetes analysis",
    "kubernetes design",
    "kubernetes modeling",
    "kubernetes optimization",
    "kubernetes simulation",
    "kubernetes testing",
    "linux",
    "linux analysis",
    "linux design",
    "linux modeling",
    "linux optimization",
    "linux simulation",
    "linux testing",
    "machine learning",
    "machine learning analysis",
    "machine learning design",
    "machine learning modeling",
    "machine learning optimization",
    "machine learning simulation",
    "machine learning testing",
    "ml",
    "microservices",
    "microservices analysis",
    "microservices design",
    "microservices modeling",
    "microservices optimization",
    "microservices simulation",
    "microservices testing",
    "mongodb",
    "mongodb analysis",
    "mongodb design",
    "mongodb modeling",
    "mongodb optimization",
    "mongodb simulation",
    "mongodb testing",
    "mysql",
    "mysql analysis",
    "mysql design",
    "mysql modeling",
    "mysql optimization",
    "mysql simulation",
    "mysql testing",
    "neural networks",
    "neural networks analysis",
    "neural networks design",
    "neural networks modeling",
    "neural networks optimization",
    "neural networks simulation",
    "neural networks testing",
    "nlp",
    "nlp analysis",
    "nlp design",
    "nlp modeling",
    "nlp optimization",
    "nlp simulation",
    "nlp testing",
    "nosql",
    "nosql analysis",
    "nosql design",
    "nosql modeling",
    "nosql optimization",
    "nosql simulation",
    "nosql testing",
    "postgresql",
    "postgresql analysis",
    "postgresql design",
    "postgresql modeling",
    "postgresql optimization",
    "postgresql simulation",
    "postgresql testing",
    "python",
    "python analysis",
    "python design",
    "python modeling",
    "python optimization",
    "python simulation",
    "python testing",
    "pytorch",
    "pytorch analysis",
    "pytorch design",
    "pytorch modeling",
    "pytorch optimization",
    "pytorch simulation",
    "pytorch testing",
    "rest analysis",
    "rest design",
    "rest modeling",
    "rest optimization",
    "rest simulation",
    "rest testing",
    "rust",
    "rust analysis",
    "rust design",
    "rust modeling",
    "rust optimization",
    "rust simulation",
    "rust testing",
    "scikit-learn",
    "scikit-learn analysis",
    "scikit-learn design",
    "scikit-learn modeling",
    "scikit-learn optimization",
    "scikit-learn simulation",
    "scikit-learn testing",
    "spark",
    "spark analysis",
    "spark design",
    "spark modeling",
    "spark optimization",
    "spark simulation",
    "spark testing",
    "sql",
    "sql analysis",
    "sql design",
    "sql modeling",
    "sql optimization",
    "sql simulation",
    "sql testing",
    "tensorflow",
    "tensorflow analysis",
    "tensorflow design",
    "tensorflow modeling",
    "tensorflow optimization",
    "tensorflow simulation",
    "tensorflow testing",
    "typescript",
    "typescript analysis",
    "typescript design",
    "typescript modeling",
    "typescript optimization",
    "typescript simulation",
    "typescript testing",
    "heat exchanger",
    "finite element analysis",
    "thermodynamics",
    "fluid dynamics",
    "structural analysis",
    "hvac design",
    "machine design",
    "kinematics",
    "dynamics",
    "stress analysis",
    "vibration analysis",
    "control systems",
    "mechanical design",
    "turbomachinery",
    "material science",
    "mechatronics",
    "robotics",
    "mechanical testing",
    "design optimization",
    "computational fluid dynamics",
    "mechanical assembly",
    "thermal analysis",
    "rotating equipment",
    "load calculation",
    "mechanical prototyping",
    "mechanical drafting",
    "mechanical modeling",
    "mechanical simulation",
    "solidworks",
    "autocad",
    "catia",
    "ansys",
    "matlab",
    "labview",
    "revit",
    "creo",
    "inventor",
    "nx",
    "comsol multiphysics",
    "autodesk inventor",
    "ptc creo",
    "fusion 360",
    "blueprint reading",
    "prototype development",
    "experimental setup",
    "data acquisition",
    "design validation",
    "manufacturing process",
    "3d printing",
    "machine maintenance",
    "mechanical testing procedures",
    "mechanical assembly line",
    "quality control inspection",
    "asme",
    "iso 9001",
    "lean manufacturing",
    "six sigma",
    "osha",
    "pmp",
    "eit",
    "fe",
    "pe",
    "mass transfer",
    "heat transfer",
    "fluid mechanics",
    "process simulation",
    "process safety management",
    "chemical reaction engineering",
    "thermodynamics",
    "material balances",
    "distillation",
    "separation processes",
    "kinetics",
    "catalysis",
    "chemical process optimization",
    "pilot plant operation",
    "reaction modeling",
    "chemical process control",
    "chemical engineering design",
    "aspen hysys",
    "aspen plus",
    "chemcad",
    "matlab",
    "comsol",
    "autocad",
    "labview",
    "pilot plant operation",
    "reactor design",
    "process optimization",
    "pid development",
    "experimental procedure",
    "sampling and analysis",
    "process safety audits",
    "chemical testing",
    "osha",
    "api",
    "iso 9001",
    "six sigma",
    "lean manufacturing",
    "eit",
    "fe",
    "pe",
    "circuit design",
    "power systems",
    "signal processing",
    "embedded systems",
    "control systems",
    "plc programming",
    "digital logic design",
    "microcontrollers",
    "communication systems",
    "power electronics",
    "analog circuits",
    "digital circuits",
    "semiconductor devices",
    "matlab",
    "simulink",
    "spice",
    "autocad electrical",
    "labview",
    "multisim",
    "altium designer",
    "kicad",
    "python",
    "c++",
    "c#",
    "verilog",
    "vhdl",
    "proteus",
    "arduino ide",
    "pcb design",
    "system integration",
    "testing and validation",
    "data acquisition",
    "firmware development",
    "troubleshooting",
    "schematic analysis",
    "hardware debugging",
    "ieee",
    "nec",
    "osha",
    "lean manufacturing",
    "six sigma",
    "eit",
    "fe",
    "pe",
    "algorithms",
    "data structures",
    "machine learning",
    "deep learning",
    "natural language processing",
    "software architecture",
    "object oriented programming",
    "web development",
    "database design",
    "cloud computing",
    "cybersecurity",
    "artificial intelligence",
    "computer vision",
    "distributed systems",
    "python",
    "c++",
    "java",
    "c#",
    "javascript",
    "sql",
    "html",
    "css",
    "tensorflow",
    "pytorch",
    "react",
    "node.js",
    "aws",
    "git",
    "docker",
    "kubernetes",
    "bash scripting",
    "linux",
    "firebase",
    "version control",
    "api development",
    "code review",
    "unit testing",
    "integration testing",
    "ci/cd",
    "agile methodology",
    "scrum",
    "devops",
    "microservices",
    "containerization",
    "software debugging",
    "aws certified developer",
    "comptia security+",
    "scrum master",
    "pmp",
    "lean six sigma",
    "heat exchanger design",
    "finite element analysis simulation",
    "process safety management",
    "structural integrity assessment",
    "circuit board layout",
    "machine learning model development",
    "data visualization and reporting",
    "prototype testing and validation",
    "electrical load calculation",
    "process optimization and control",
    "mechanical design optimization",
    "thermodynamic cycle analysis",
    "chemical process simulation",
    "embedded system programming",
    "software development lifecycle",
    "database schema design",
    "cloud infrastructure deployment",
    "version control management",
    "pilot plant process operation",
    "plc programming and automation",
    "project planning and management",
    "computational fluid dynamics modeling",
    "signal processing algorithm development",
    "molecular spectroscopy",
    "FTIR",
    "XRAY",
    "IR",
    "UV/Vis",
    "DCS",
    "SIS",
    "HAZOP",
    "Honeywell",
    "Emerson",
    "Risk Assessment"

]







